### ISSUE TITLE
trouble at bot.py

### ISSUE THREAD

**Issue by koushikvasu** [HackerShackOfficial/AI-Smart-Mirror#95]
HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /microphone?enabled=False (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x761a6910>: Failed to establish a new connection: [Errno 111] Connection refused',))
Traceback (most recent call last):
  File "bot.py", line 254, in <module>
    bot.start()
  File "bot.py", line 39, in start
    requests.get("http://localhost:8080/clear")
  File "/home/pi/AI-Smart-Mirror/hhsmartmirror/local/lib/python2.7/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/home/pi/AI-Smart-Mirror/hhsmartmirror/local/lib/python2.7/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/pi/AI-Smart-Mirror/hhsmartmirror/local/lib/python2.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/pi/AI-Smart-Mirror/hhsmartmirror/local/lib/python2.7/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/home/pi/AI-Smart-Mirror/hhsmartmirror/local/lib/python2.7/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /clear (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x761a6b50>: Failed to establish a new connection: [Errno 111] Connection refused',))

**Comment by vijayPagi** [comment]
Did you get to resolved this error... Else, Can someone please help...Thank you in Advance
